SELECT CITY,
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE DAYOFWEEK_='01.PZT' AND CITY=S.CITY) AS PAZARTESI,
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE DAYOFWEEK_='02.SAL' AND CITY=S.CITY) AS SALI,
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE DAYOFWEEK_='03.ÇAR' AND CITY=S.CITY) AS CARSAMBA,
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE DAYOFWEEK_='04.PER' AND CITY=S.CITY) AS PERSEMBE,
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE DAYOFWEEK_='05.CUM' AND CITY=S.CITY) AS CUMA,
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE DAYOFWEEK_='06.CMT' AND CITY=S.CITY) AS CUMARTESI,
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE DAYOFWEEK_='07.PAZ' AND CITY=S.CITY) AS PAZAR
FROM SALEORDERS S
GROUP BY CITY 
ORDER BY 1

SELECT * FROM SALEORDERS