SELECT 
	SUM(LINENET) AS TOLAMSATIS, 
	COUNT(*) AS SATIRSAYISI, 
	MIN(LINENET) AS ENDUDUKFIYAT, 
	MAX(LINENET) AS ENYUKSEKFIYAT, 
	AVG (LINENET) AS ORTALAMASATISFIYATI
FROM SALES WHERE BRANCH='Rize Subesi'

SELECT * FROM SALES WHERE BRANCH LIKE 'Rize%'