SELECT * FROM SALES
--ÞUBEYE GÖRE EN YÜKSEK SATIÞ SIRALAMASI
SELECT
	TOP 10
	BRANCH AS SUBEADI, 
	SUM (LINENET) AS SATISTAOPLAMI 
FROM SALES
GROUP BY BRANCH ORDER BY SUM (LINENET) DESC

--TOPLAM SATIÞI 50.000 DEN BÜYÜK OLANLAR

SELECT 
	BRANCH AS SUBEADI,
	SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY BRANCH
HAVING SUM (LINENET)>50000 -- FONKSÝYONLU ÞART KULLANILACAK ÝSE HAVING KULLANILIR. -- GROUP BY DAN SONRA KULLANILIR