-- SUBQUERY ÝLE MÜÞTERÝ BÝLGÝLERÝ GETÝRME

SELECT
U.ID,
U.NAMESURNAME,
	(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) AS SEPETSAYISI,
	(SELECT MIN (CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS ILKSIPARIS,
	(SELECT MAX (CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS SONSIPARIS,
	(SELECT SUM(TOTAL) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) AS TOTAL,
	(SELECT COUNT(*) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) AS SIPARISAYISI,
	(SELECT ITEMNAME FROM ITEM WHERE ID IN
		(SELECT TOP 1 ITEMID FROM BASKETDETAIL WHERE BASKETID IN 
			(SELECT ID FROM BASKET WHERE USERID=U.ID)
	ORDER BY DATE_ DESC
	)
	) AS SONSIPARIS
FROM USER_ U


WHERE (SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)>0