--HER BÝR KULLANICININ KAÇ TANE ADRESÝ VAR 

SELECT 
	U.USERNAME_ AS KULLANICIADI,
	U.NAMESURNAME AS ADSOYAD,
	U.EMAIL,
	U.TELNR1 AS TELEFON1,
	U.TELNR2 AS TELEFON2,
	COUNT (A.ID) AS ADRESSAYISI
FROM USER_ AS U
		JOIN ADDRES AS A ON U.ID=A.USERID
		JOIN CITY AS C ON C.ID=A.CITYID
		JOIN TOWN AS T ON T.ID=A.TOWNID
		JOIN DISTRICT D ON D.ID=A.DISTRICTID
GROUP BY U.USERNAME_,
	U.NAMESURNAME,
	U.EMAIL,
	U.TELNR1,
	U.TELNR2 
HAVING COUNT(A.ID)=4
ORDER BY COUNT(A.ID) DESC
		  