--SELECT TOP 4 PERCENT * FROM CUSTOMER -- ÝLK DÖRT KAYITI GETÝRÝR


--SELECT TOP 4 PERCENT * FROM CUSTOMER -- ÞEHRÝ ÝSTANBUL OLUP ÝSME GÖRE KÜÇÜKTEN BÜYÜÐE SIRALI OLMASI ÞARTIYLA KAYITLARIN ÝLK YÜZDE 4 ÜNÜ GETÝRÝR.
--WHERE CITY='ÝSTANBUL'
--ORDER BY NAME 