--BÝR MAÐAZANIN GÜN BAZLI SATIÞ RAKAMLARI

 SELECT 
 BRANCH AS SUBE,
 DATE_ AS TARIH,
 SUM (LINENET) AS TOPLAMSATIS,
 COUNT (BRANCH) AS SATIRSAYISI
 FROM SALES 
 WHERE BRANCH='BURSA SUBESÝ' AND DATE_='2017-01-05'
 GROUP BY BRANCH, DATE_