--HANGÝ ÞEHÝRDE KAÇ KULLANICI VAR

SELECT 
	C.CITY,
	COUNT ( U.ID) AS KULLANICISAYISI

FROM USER_ AS U
		JOIN ADDRES AS A ON U.ID=A.USERID
		JOIN CITY AS C ON C.ID=A.CITYID
		
GROUP BY C.CITY
ORDER BY COUNT(A.ID) DESC
