SELECT
U.USERNAME_,B.CREATEDDATE, BD.AMOUNT,BD.PRICE,BD.TOTAL,
I.ITEMCODE,I.ITEMNAME,I.CATEGORY1,I.CATEGORY1,I.CATEGORY3,
A.ADDRESSTEXT,C.CITY,T.TOWN,D.DISTRICT,
INV.INVOICENO,
INV.CARGOFICHENO,
INV.DATE_

FROM USER_ U
INNER JOIN BASKET B ON B.USERID =U.ID 
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
INNER JOIN ITEM I ON I.ID=BD.ID
INNER JOIN ORDER_ O ON O.BASKETID=B.ID
INNER JOIN ADDRES A ON A.ID=O.ADDRESSID
INNER JOIN CITY C ON C.ID=A.CITYID
INNER JOIN TOWN T ON T.ID=A.TOWNID
INNER JOIN DISTRICT  D ON D.ID=A.DISTRICTID
INNER JOIN INVOICE INV ON INV.ORDERID=O.ID



