--LOWER,UPPER,REVERSE,REPLICATE



SELECT LOWER ('SÝNEM')--BÜYÜK HARFÝ KÜÇÜK HARFE DÖNÜÞTÜRÜR
SELECT UPPER ('sinem')--KÜYÜK HARFÝ BÜÇÜK HARFE DÖNÜÞTÜRÜR
SELECT REVERSE ('SÝNEM KOPUZ')--TERS YAZMA
SELECT REPLICATE ('0',8) 