--LEFT,RIGHT,LEN

SELECT LEFT ('SÝNEM KOPUZ',2)--SOLDAN ÝLK 2 KARAKTER
SELECT RIGHT ('SÝNEM KOPUZ',3)--SAÐDAN ÝLK 3 KARAKTER
SELECT LEN('SÝNEM')--KAÇ KARAKTER OLDUÐU

SELECT 
LEFT (NAMESURNAME, CHARINDEX (' ',NAMESURNAME)) AS AD ,
RIGHT (NAMESURNAME, LEN(NAMESURNAME)-CHARINDEX (' ',NAMESURNAME)) AS SOYAD
FROM USER_
