--CONCAT


SELECT CONCAT ('SÝNEM',' ','FATÝH',' ','ERDOÐAN')
SELECT CONCAT_WS(' ','SÝNEM','FATÝH','ERDOÐAN')


SELECT 

CONCAT (USERNAME_,' ',PASSWORD_,' ',NAMESURNAME),
CONCAT_WS (' ', USERNAME_ ,PASSWORD_ ,NAMESURNAME)

FROM USER_