--BÝR MÜÞTERÝNÝN GÝTTÝÐÝ MAÐAZALAR

--SELECT * FROM SALES

SELECT 
 CLIENTNAME AS MUSTERÝ,
 COUNT (DISTINCT BRANCH) AS MAGAZASAYISI
 FROM SALES
 GROUP BY CLIENTNAME
 HAVING COUNT (DISTINCT BRANCH)>10
 ORDER BY CLIENTNAME 

