SELECT 
	BRANCH,
	SUM(LINENET) AS TOLAMSATIS, 
	COUNT(*) AS SATIRSAYISI, 
	MIN(LINENET) AS ENDUDUKFIYAT, 
	MAX(LINENET) AS ENYUKSEKFIYAT, 
	AVG (LINENET) AS ORTALAMASATISFIYATI
FROM SALES 
GROUP BY BRANCH

SELECT * FROM SALES WHERE BRANCH LIKE 'Rize%'