--EN ÇOK SATIÞ YAPILAN ÜRÜN KATEGORÝLERÝ



SELECT 
CATEGORY1,
SUM ( OD.TOTALPRICE) AS TOTAL
FROM ITEM I
INNER JOIN ORDERDETAIL OD ON OD.ITEMID =I.ID
INNER JOIN ORDER_ O ON O.ID =OD.ORDERID
GROUP BY I.CATEGORY1
