SELECT 
	U.USERNAME_ AS KULLANICIADI,
	U.NAMESURNAME AS ADSOYAD,
	U.EMAIL,
	U.TELNR1 AS TELEFON1,
	U.TELNR2 AS TELEFON2,
	C.CITY AS SEHIR,
	T.TOWN AS ILCE,
	D.DISTRICT AS MAHALLE, 
	A.ADDRESSTEXT AS ACIKADRES
FROM USER_ AS U
		JOIN ADDRES AS A ON U.ID=A.USERID
		JOIN CITY AS C ON C.ID=A.CITYID
		JOIN TOWN AS T ON T.ID=A.TOWNID
		JOIN DISTRICT D ON D.ID=A.DISTRICTID
		  