--SELECT * FROM CUSTOMER WHERE AGE=28

--SELECT * FROM CUSTOMER WHERE AGE<28

--SELECT * FROM CUSTOMER WHERE AGE BETWEEN 20 AND 30

--SELECT * FROM CUSTOMER WHERE NAME LIKE '%UZ' -- SONU UZ ÝLE BÝTENLER

--SELECT * FROM CUSTOMER WHERE NAME LIKE '%UZ%' -- ÝÇÝNDE UZ GEÇENLER

--SELECT * FROM CUSTOMER WHERE NAME LIKE 'SÝNEM%' -- SÝNEM ÝLE BAÞLAYANLAR

--SELECT * FROM CUSTOMER WHERE CITY='ÝSTANBUL' AND DISTRICT IN ('PENDÝK','KADIKÖY') --ÝLÝ ÝSTANBUL ÝLÇESÝ PENDÝK KADIKÖY OLANLAR

--SELECT * FROM CUSTOMER WHERE CITY='ÝSTANBUL' AND DISTRICT NOT IN ('PENDÝK','KADIKÖY') -- ÝLÝ ÝSTANBUL ÝLÇESÝ PENDÝK KADIKÖY OLMAYANLAR

--UPDATE CUSTOMER SET GENDER='ERKEK' WHERE GENDER='E' -- CÝNSÝYETÝ E OLANLARI ERKEK OLARAK DÜZENLE

--UPDATE CUSTOMER SET GENDER='KADIN' WHERE GENDER='K'


