--EN ÇOK SATIÞ YAPILAN MÜÞTERÝLER


SELECT TOP 10
U.NAMESURNAME,
SUM (BD.ID) AS TOTAL
FROM USER_ U
INNER JOIN BASKET B ON B.USERID = U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID = B.ID
GROUP BY U.NAMESURNAME
ORDER BY SUM (BD.ID) DESC

