SELECT 
C.CITY,
D.DISTRICT,
COUNT (CT.ID) AS MUSTERISAYISI
FROM CUSTOMERS CT
INNER JOIN DISTRICTS D ON D.ID=CT.DISTRICTID
INNER JOIN CITYS C ON C.ID=D.CITYID
GROUP BY D.DISTRICT,C.CITY
ORDER BY C.CITY ,D.DISTRICT,COUNT (CT.ID) DESC


SELECT * FROM CUSTOMERS WHERE CITYID=34