UPDATE CUSTOMERS SET AGEGROUP='20-35 YAÞ '
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35

UPDATE CUSTOMERS SET AGEGROUP='35-45 YAÞ '
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 35 AND 45

UPDATE CUSTOMERS SET AGEGROUP='45-55 YAÞ '
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 45 AND 55

UPDATE CUSTOMERS SET AGEGROUP='55+ YAÞ '
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE())>55

UPDATE CUSTOMERS SET AGEGROUP='20 YAÞ '
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE())<20
SELECT * FROM CUSTOMERS