SELECT 
CY.CITY AS SEHÝR,
(SELECT COUNT(*) FROM CUSTOMERS C WHERE  C.CITYID=CY.ID AND C.GENDER='K') AS KADINSAYISI,
(SELECT COUNT(*)  FROM CUSTOMERS C WHERE   C.CITYID=CY.ID AND  C.GENDER='E') AS ERKEKSAYISI
FROM CITYS CY


