SELECT 
(SELECT COUNT (ID) FROM CUSTOMERS WHERE TELNR1 LIKE '(50%'  OR TELNR1 LIKE '(55%' )  AS X,
(SELECT COUNT (ID) FROM CUSTOMERS WHERE TELNR1 LIKE '(53%' ) AS Y,
(SELECT COUNT (ID) FROM CUSTOMERS WHERE TELNR1 LIKE '(54%' )AS Z



SELECT TELNR1 FROM CUSTOMERS