SELECT 

	CASE
		
		WHEN DATEDIFF (YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAÞ'
		WHEN DATEDIFF (YEAR,BIRTHDATE,GETDATE()) BETWEEN 35 AND 45 THEN '35-45 YAÞ'
		WHEN DATEDIFF (YEAR,BIRTHDATE,GETDATE()) BETWEEN 45 AND 55 THEN '45-55 YAÞ'
		WHEN DATEDIFF (YEAR,BIRTHDATE,GETDATE())>55 THEN '55+'
		END AGEGROUP2,
		COUNT (*)
FROM CUSTOMERS
GROUP BY 
CASE
		
		WHEN DATEDIFF (YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAÞ'
		WHEN DATEDIFF (YEAR,BIRTHDATE,GETDATE()) BETWEEN 35 AND 45 THEN '35-45 YAÞ'
		WHEN DATEDIFF (YEAR,BIRTHDATE,GETDATE()) BETWEEN 45 AND 55 THEN '45-55 YAÞ'
		WHEN DATEDIFF (YEAR,BIRTHDATE,GETDATE())>55 THEN '55+'
		END 
	ORDER BY 1
