SELECT 
P.NAME+' '+P.SURNAME,
PS.POSITION,
P1.NAME+' '+P1.SURNAME AS AMIR,
PS3.POSITION AS AMIRPOZISYONU
FROM PERSON P

INNER JOIN POSITION PS ON PS.ID=P.POSITIONID
INNER JOIN PERSON P1 ON P1.ID=P.MANAGERID
INNER JOIN POSITION PS3 ON PS3.ID=P1.POSITIONID
