SELECT 
PS.POSITION,
MIN(P.SALARY) MINMAAS,
MAX(P.SALARY) MAXMAAS,
AVG(P.SALARY) ORTALAMAMAAS

FROM PERSON P
INNER JOIN POSITION PS ON PS.ID=P.POSITIONID
WHERE PS.POSITION='PLANLAMA ÞEFÝ'
GROUP BY PS.POSITION