SELECT 
	D.DEPARTMENT,
	CASE
		WHEN P.GENDER='K' THEN 'KADIN'
		WHEN P.GENDER='E' THEN 'ERKEK' --ELSE DE KULLANILABÝLÝR
	END AS GENDER,

	COUNT (P.ID) AS SAYI
FROM PERSON P
INNER JOIN DEPARTMENT D ON D.ID=P.DEPARTMENTID
WHERE OUTDATE IS NULL
GROUP BY D.DEPARTMENT,P.GENDER
ORDER BY 1,3 DESC
