SELECT 
YEAR(P.INDATE) AS YIL,
(SELECT COUNT (P1.ID) FROM PERSON P1 WHERE GENDER='K' AND  YEAR(P1.INDATE)= YEAR(P.INDATE)) AS KADIN,
(SELECT COUNT(P2.ID) FROM PERSON P2 WHERE GENDER='E' AND  YEAR(P2.INDATE)= YEAR(P.INDATE)) AS ERKEK
FROM PERSON P
GROUP BY YEAR(P.INDATE)
